server:
  port: 8889
  tomcat:
    max-swallow-size: -1
    max-http-post-size: 10MB



#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/wolf-cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#    username: root
#    password: liangkeyiwei
#    type: com.alibaba.druid.pool.DruidDataSource
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: file:D:/liangkeyiwei/IMGS


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wolf-cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:D:/liangkeyiwei/IMGS



webservices:
  userName: admin
  passWord: 123456

mybatis:
  mapper-locations: classpath:cn.com.busi.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置pagehelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  config: classpath:logback-spring.xml
  path: d:/liangkeyiwei/logs
#  level: cn.com.busi.mapper = debug








